// src/lib/utils/merge-prisma.ts
import fs from 'fs/promises';
import path from 'path';

async function mergePrismaSchemas(): Promise<void> {
  console.log('🚀 Starting Prisma schema merge...');
  
  try {
    const projectRoot = process.cwd();
    const modelDir = path.join(projectRoot, 'prisma/models');
    const outputFile = path.join(projectRoot, 'prisma/schema.prisma');
    
    console.log('📂 Project root:', projectRoot);
    console.log('🔍 Model directory:', modelDir);
    
    // Check if directory exists
    try {
      await fs.access(modelDir);
      console.log('✅ Found models directory');
    } catch {
      console.log('📁 Creating models directory...');
      await fs.mkdir(modelDir, { recursive: true });
    }
    
    // Read files
    let files: string[];
    try {
      files = await fs.readdir(modelDir);
      console.log(`📄 Found ${files.length} files in models/`);
    } catch (error) {
      console.error('❌ Error reading directory:', error);
      files = [];
    }
    
    // Filter .prisma files
    const prismaFiles = files.filter(file => file.endsWith('.prisma'));
    console.log(`🔍 Found ${prismaFiles.length} .prisma files:`, prismaFiles);
    
    if (prismaFiles.length === 0) {
      console.log('⚠️  No .prisma files found.');
      console.log('💡 Create files like: User.prisma, Role.prisma in prisma/models/');
      return;
    }
    
    // Create merged schema
    let mergedSchema = `// Auto-generated by merge-prisma.ts
// Generated: ${new Date().toISOString()}
// Models: ${prismaFiles.join(', ')}

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;
    
    // Add imports
    mergedSchema += '\n// Import model files\n';
    for (const file of prismaFiles) {
      mergedSchema += `import "./models/${file}"\n`;
      console.log(`  ➕ Importing: ${file}`);
    }
    
    // Write output
    await fs.writeFile(outputFile, mergedSchema, 'utf-8');
    console.log(`✅ Successfully created: ${outputFile}`);
    console.log('🎉 Done!');
    
  } catch (error) {
    console.error('❌ Fatal error:', error);
    throw error;
  }
}

// Simple execution check - this works with both tsx and node
if (process.argv[1] === __filename || process.argv[1].includes('merge-prisma.ts')) {
  mergePrismaSchemas().catch(error => {
    console.error('Failed:', error);
    process.exit(1);
  });
}

export { mergePrismaSchemas };