// src/lib/utils/merge-prisma.ts
import fs from 'fs/promises';
import path from 'path';

async function main() {
  try {
    const projectRoot = process.cwd();
    const modelDir = path.join(projectRoot, 'prisma/models');
    const outputFile = path.join(projectRoot, 'prisma/schema.prisma');
    
    // Ensure directories exist
    await fs.mkdir(path.dirname(outputFile), { recursive: true });
    await fs.mkdir(modelDir, { recursive: true });
    
    // Get .prisma files
    let files: string[] = [];
    try {
      files = await fs.readdir(modelDir);
    } catch (error) {
    }
    
    const prismaFiles = files.filter((f: string) => f.endsWith('.prisma'));
    
    if (prismaFiles.length === 0) {
      return;
    }
    
    // Display files
    prismaFiles.forEach(file => console.log(`  • ${file}`));
    
    // Build schema - WITHOUT import statements
    let schema = `// Auto-generated by merge-prisma.ts
// Generated: ${new Date().toISOString()}
// Models: ${prismaFiles.join(', ')}

generator client {
  provider = "prisma-client-js"
  output   = "../src/generated/prisma"
}

datasource db {
  provider = "postgresql"
  // url = env("DATABASE_URL") - Configure in PrismaClient instead
}

`;
    
    // Read and append each file's CONTENT (not import statements)
    for (const file of prismaFiles) {
      const filePath = path.join(modelDir, file);
      const content = await fs.readFile(filePath, 'utf-8');
      
      // Add separator and the actual model content
      schema += `\n// ========== ${file} ==========\n`;
      schema += content.trim() + '\n';
    }
    
    // Write to file
    await fs.writeFile(outputFile, schema, 'utf-8');
    
  } catch (error: any) {
    console.error('❌ Error:', error.message);
    process.exit(1);
  }
}

// Execute
main();