@echo off
setlocal enabledelayedexpansion

echo ============================================
echo  COMBINING PRISMA MODELS
echo ============================================

REM Check if models directory exists
if not exist "prisma\models" (
    echo ❌ ERROR: Models directory not found: prisma\models
    echo Creating models directory...
    mkdir "prisma\models"
    if errorlevel 1 (
        echo ❌ Failed to create models directory
        exit /b 1
    )
)

REM Check if there are model files
set "fileCount=0"
for %%f in (prisma\models\*.prisma) do set /a "fileCount+=1"

if %fileCount% == 0 (
    echo ⚠️ WARNING: No .prisma files found in prisma\models\
    echo Place your model files in prisma\models\ folder
    echo Example: User.prisma, Plan.prisma, etc.
)

REM Generate the schema file
echo Generating schema.prisma...

REM Create base schema with proper formatting
(
echo // ============================================
echo // AUTO-GENERATED - DO NOT EDIT DIRECTLY
echo // Generated by combine-models.bat
echo // Date: %date% %time%
echo // ============================================
echo.
echo generator client {
echo   provider = "prisma-client-js"
echo }
echo.
echo datasource db {
echo   provider = "postgresql"
echo   url      = env("DATABASE_URL")
echo }
echo.
echo // ============================================
echo // ENUMS
echo // ============================================
echo.
) > "prisma\schema.prisma"

REM First extract and add all enums
set "enumAdded=0"
for %%f in (prisma\models\*.prisma) do (
    echo Processing enums from: %%~nxf
    findstr /B "enum" "%%f" >nul 2>&1
    if not errorlevel 1 (
        set /a "enumAdded+=1"
        echo // From: %%~nxf >> "prisma\schema.prisma"
        (for /f "delims=" %%a in ('findstr /B "enum" "%%f"') do echo %%a) >> "prisma\schema.prisma"
        echo. >> "prisma\schema.prisma"
    )
)

if %enumAdded% == 0 (
    echo // No enums found in model files >> "prisma\schema.prisma"
    echo. >> "prisma\schema.prisma"
)

REM Add separator for models
(
echo // ============================================
echo // MODELS
echo // ============================================
echo.
) >> "prisma\schema.prisma"

REM Add all model files (excluding enums that were already added)
set "modelAdded=0"
for %%f in (prisma\models\*.prisma) do (
    echo Adding model: %%~nxf
    set /a "modelAdded+=1"
    echo // --- File: %%~nxf --- >> "prisma\schema.prisma"
    
    REM Read file line by line, skipping enum blocks
    set "inEnum=0"
    for /f "delims=" %%a in ('type "%%f"') do (
        set "line=%%a"
        
        REM Check if line starts with "enum"
        echo !line! | findstr /B "enum" >nul 2>&1
        if not errorlevel 1 (
            set "inEnum=1"
        )
        
        REM Check if line is empty (end of enum)
        if "!line!"=="" set "inEnum=0"
        
        REM If not in enum block, write the line
        if !inEnum!==0 (
            echo !line! >> "prisma\schema.prisma"
        ) else (
            REM If we're at the end of enum (closing brace on same line)
            echo !line! | findstr "}" >nul 2>&1
            if not errorlevel 1 (
                set "inEnum=0"
            )
        )
    )
    echo. >> "prisma\schema.prisma"
    echo. >> "prisma\schema.prisma"
)

REM Final output
echo ============================================
echo ✅ SCHEMA GENERATION COMPLETE
echo.
echo 📊 Statistics:
echo    Model files processed: %modelAdded%
echo    Enum files found: %enumAdded%
echo    Output file: prisma\schema.prisma
echo.
echo ⚡ Next steps:
echo    1. Run: npx prisma generate
echo    2. Run: npx prisma migrate dev
echo ============================================

REM Open the generated file in default editor (optional)
REM start "" "prisma\schema.prisma"

endlocal